2021-07-30 16:28:58,449 ERROR -> in command: set
Traceback (most recent call last):
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\cogs\Settings.py", line 89, in set
    mes = self.bot.reset_settings(ctx.guild.id)
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\bot.py", line 264, in reset_settings
    cur.execute('''UPDATE servers SET style=? graph=? WHERE id=?''',
sqlite3.OperationalError: near "graph": syntax error


2021-07-30 17:32:33,988 ERROR -> Attempting a reconnect in 1.29s
Traceback (most recent call last):
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 566, in connect
    await self.ws.poll_event()
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\gateway.py", line 582, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000


2021-07-30 18:09:38,416 ERROR -> in command: set
Traceback (most recent call last):
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\cogs\Settings.py", line 139, in set
    mes = self.bot.set_setting(ctx.guild.id, settingType, default)
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\bot.py", line 291, in set_setting
    cur.execute('''SELECT FROM servers
sqlite3.OperationalError: near "FROM": syntax error


2021-08-02 17:11:36,345 ERROR -> in command: yes
Traceback (most recent call last):
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\cogs\Table.py", line 423, in yes
    self.bot.table_instances[ctx.channel.id].populate_table_flags()
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\tabler.py", line 374, in populate_table_flags
    raise exc
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\tabler.py", line 372, in populate_table_flags
    mii_result = future.result()
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\utils\WiimmfiMii.py", line 23, in get_wiimmfi_mii
    return WiimmfiMii(mii_data)
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\utils\WiimmfiMii.py", line 33, in __init__
    self.unknown1 = bytes(fullWiimmfiResponse[76]) #set to null
IndexError: bytearray index out of range


2021-08-03 14:09:23,996 ERROR -> in command: changetag
Traceback (most recent call last):
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\cogs\Table.py", line 320, in changetag
    mes= self.bot.table_instances[ctx.channel.id].change_tag(pID, tag)
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\tabler.py", line 766, in change_tag
    for indx, i in list(map(lambda l: Utils.sanitize_uni(l.strip).lower(),self.tags.keys())):
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\tabler.py", line 766, in <lambda>
    for indx, i in list(map(lambda l: Utils.sanitize_uni(l.strip).lower(),self.tags.keys())):
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\utils\Utils.py", line 137, in sanitize_uni
    for i in string:
TypeError: 'builtin_function_or_method' object is not iterable


2021-08-03 14:10:45,851 ERROR -> in command: changetag
Traceback (most recent call last):
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\cogs\Table.py", line 320, in changetag
    mes= self.bot.table_instances[ctx.channel.id].change_tag(pID, tag)
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\tabler.py", line 766, in change_tag
    for indx, i in list(map(lambda l: Utils.sanitize_uni(l.strip).lower(),list(self.tags.keys()))):
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\tabler.py", line 766, in <lambda>
    for indx, i in list(map(lambda l: Utils.sanitize_uni(l.strip).lower(),list(self.tags.keys()))):
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\utils\Utils.py", line 137, in sanitize_uni
    for i in string:
TypeError: 'builtin_function_or_method' object is not iterable


2021-08-03 14:14:12,471 ERROR -> in command: changetag
Traceback (most recent call last):
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\cogs\Table.py", line 320, in changetag
    mes= self.bot.table_instances[ctx.channel.id].change_tag(pID, tag)
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\tabler.py", line 766, in change_tag
    for indx, i in enumerate(list(map(lambda l: Utils.sanitize_uni(l.strip).lower(),self.tags.keys()))):
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\tabler.py", line 766, in <lambda>
    for indx, i in enumerate(list(map(lambda l: Utils.sanitize_uni(l.strip).lower(),self.tags.keys()))):
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\utils\Utils.py", line 137, in sanitize_uni
    for i in string:
TypeError: 'builtin_function_or_method' object is not iterable


2021-08-03 14:33:51,910 ERROR -> in command: playerlist
Traceback (most recent call last):
  File "C:\Users\ryanz\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\Users\ryanz\OneDrive\Desktop\Table-BOT\cogs\Table.py", line 733, in playerlist
    await self.send_messages(ctx, self.bot.table_instances[ctx.channel.id].get_player_list(p_form=False, include_tags=False))
TypeError: get_player_list() got an unexpected keyword argument 'include_tags'


